version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: django_crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres